import { useMemo, useState } from "react"
import { useNavigate } from "react-router-dom"
import {
  FiDownload,
  FiEye,
  FiFileText,
  FiSearch,
  FiX,
} from "react-icons/fi"
import { toast } from "react-toastify"

import Card from "../../components/Card"
import Badge from "../../components/Badge"
import Button from "../../components/Button"
import { reportsData } from "../../data/reportsData"

const Reports = () => {
  const navigate = useNavigate()

  const [search, setSearch] = useState("")
  const [typeFilter, setTypeFilter] = useState("All")
  const [selectedReport, setSelectedReport] = useState(null)

  const filteredReports = useMemo(() => {
    const value = search.toLowerCase().trim()

    return reportsData.filter((report) => {
      const matchesSearch =
        !value ||
        report.reportName
          .toLowerCase()
          .includes(value) ||
        report.patientName
          .toLowerCase()
          .includes(value) ||
        report.patientId
          .toLowerCase()
          .includes(value) ||
        report.generatedBy
          .toLowerCase()
          .includes(value)

      const matchesType =
        typeFilter === "All" ||
        report.reportType === typeFilter

      return matchesSearch && matchesType
    })
  }, [search, typeFilter])

  const reportTypes = [
    ...new Set(
      reportsData.map((report) => report.reportType)
    ),
  ]

  const handleDownload = (report) => {
    // Dummy download action for now.
    toast.success(
      `${report.reportName} download started.`
    )
  }

  return (
    <div className="mx-auto max-w-[1400px] space-y-6">

      {/* Header */}
      <div>
        <p className="text-sm font-medium text-blue-600">
          Clinical Documentation
        </p>

        <h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">
          Reports
        </h1>

        <p className="mt-2 text-sm text-slate-500">
          View and download clinical reports generated by
          MedIntel.
        </p>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">

        <Card>
          <div className="flex items-center gap-4">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-600">
              <FiFileText className="h-5 w-5" />
            </div>

            <div>
              <p className="text-xs text-slate-400">
                Total Reports
              </p>

              <p className="text-xl font-bold text-slate-900">
                {reportsData.length}
              </p>
            </div>
          </div>
        </Card>

        <Card>
          <div className="flex items-center gap-4">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600">
              <FiFileText className="h-5 w-5" />
            </div>

            <div>
              <p className="text-xs text-slate-400">
                Generated
              </p>

              <p className="text-xl font-bold text-slate-900">
                {
                  reportsData.filter(
                    (report) =>
                      report.status === "Generated"
                  ).length
                }
              </p>
            </div>
          </div>
        </Card>

        <Card>
          <div className="flex items-center gap-4">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-purple-50 text-purple-600">
              <FiDownload className="h-5 w-5" />
            </div>

            <div>
              <p className="text-xs text-slate-400">
                Available
              </p>

              <p className="text-xl font-bold text-slate-900">
                {filteredReports.length}
              </p>
            </div>
          </div>
        </Card>

      </div>

      {/* Search and filter */}
      <Card>
        <div className="flex flex-col gap-3 sm:flex-row">

          <div className="relative flex-1">
            <FiSearch className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />

            <input
              type="text"
              value={search}
              onChange={(e) =>
                setSearch(e.target.value)
              }
              placeholder="Search report, patient, case ID, or generated by..."
              className="w-full rounded-lg border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-4 text-sm outline-none transition focus:border-blue-500 focus:bg-white focus:ring-2 focus:ring-blue-100"
            />
          </div>

          <select
            value={typeFilter}
            onChange={(e) =>
              setTypeFilter(e.target.value)
            }
            className="rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-700 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"
          >
            <option value="All">
              All report types
            </option>

            {reportTypes.map((type) => (
              <option key={type} value={type}>
                {type}
              </option>
            ))}
          </select>
        </div>
      </Card>

      {/* Reports table */}
      <Card className="overflow-hidden">
        <div className="border-b border-slate-100 px-5 py-4">
          <p className="text-sm text-slate-500">
            Showing{" "}
            <span className="font-semibold text-slate-800">
              {filteredReports.length}
            </span>{" "}
            reports
          </p>
        </div>

        {filteredReports.length > 0 ? (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[950px] text-left">

              <thead>
                <tr className="border-b border-slate-100 bg-slate-50/70">

                  <th className="px-5 py-3 text-xs font-semibold uppercase tracking-wider text-slate-400">
                    Report
                  </th>

                  <th className="px-5 py-3 text-xs font-semibold uppercase tracking-wider text-slate-400">
                    Patient
                  </th>

                  <th className="px-5 py-3 text-xs font-semibold uppercase tracking-wider text-slate-400">
                    Type
                  </th>

                  <th className="px-5 py-3 text-xs font-semibold uppercase tracking-wider text-slate-400">
                    Generated By
                  </th>

                  <th className="px-5 py-3 text-xs font-semibold uppercase tracking-wider text-slate-400">
                    Date
                  </th>

                  <th className="px-5 py-3 text-xs font-semibold uppercase tracking-wider text-slate-400">
                    Status
                  </th>

                  <th className="px-5 py-3 text-right text-xs font-semibold uppercase tracking-wider text-slate-400">
                    Actions
                  </th>

                </tr>
              </thead>

              <tbody>
                {filteredReports.map((report) => (
                  <tr
                    key={report.id}
                    className="border-b border-slate-100 transition hover:bg-slate-50/60"
                  >

                    {/* Report */}
                    <td className="px-5 py-4">
                      <div className="flex items-center gap-3">

                        <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-600">
                          <FiFileText className="h-4 w-4" />
                        </div>

                        <div>
                          <p className="text-sm font-semibold text-slate-800">
                            {report.reportName}
                          </p>

                          <p className="mt-0.5 text-xs text-slate-400">
                            {report.id}
                          </p>
                        </div>

                      </div>
                    </td>

                    {/* Patient */}
                    <td className="px-5 py-4">
                      <button
                        onClick={() =>
                          navigate(
                            `/cases/${report.patientId}`
                          )
                        }
                        className="text-left"
                      >
                        <p className="text-sm font-medium text-blue-600 hover:text-blue-700">
                          {report.patientName}
                        </p>

                        <p className="text-xs text-slate-400">
                          {report.patientId}
                        </p>
                      </button>
                    </td>

                    {/* Type */}
                    <td className="px-5 py-4">
                      <span className="rounded-lg bg-slate-100 px-2.5 py-1.5 text-xs font-medium text-slate-600">
                        {report.reportType}
                      </span>
                    </td>

                    {/* Generated By */}
                    <td className="px-5 py-4 text-sm text-slate-600">
                      {report.generatedBy}
                    </td>

                    {/* Date */}
                    <td className="whitespace-nowrap px-5 py-4 text-sm text-slate-500">
                      {report.generatedDate}
                    </td>

                    {/* Status */}
                    <td className="px-5 py-4">
                      <Badge variant="success">
                        {report.status}
                      </Badge>
                    </td>

                    {/* Actions */}
                    <td className="px-5 py-4">
                      <div className="flex justify-end gap-1">

                        <button
                          title="View report"
                          onClick={() =>
                            setSelectedReport(report)
                          }
                          className="rounded-lg p-2 text-slate-500 transition hover:bg-blue-50 hover:text-blue-600"
                        >
                          <FiEye className="h-4 w-4" />
                        </button>

                        <button
                          title="Download PDF"
                          onClick={() =>
                            handleDownload(report)
                          }
                          className="rounded-lg p-2 text-slate-500 transition hover:bg-emerald-50 hover:text-emerald-600"
                        >
                          <FiDownload className="h-4 w-4" />
                        </button>

                      </div>
                    </td>

                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="flex min-h-[280px] flex-col items-center justify-center text-center">

            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-slate-100">
              <FiSearch className="h-5 w-5 text-slate-400" />
            </div>

            <h3 className="mt-4 text-sm font-semibold text-slate-800">
              No reports found
            </h3>

            <p className="mt-1 text-sm text-slate-500">
              Try changing your search or report type filter.
            </p>

          </div>
        )}
      </Card>

      {/* Report Preview Modal */}
      {selectedReport && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4 backdrop-blur-sm">

          <div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white shadow-2xl">

            {/* Modal Header */}
            <div className="flex items-center justify-between border-b border-slate-100 px-6 py-5">

              <div>
                <p className="text-xs font-medium uppercase tracking-wider text-blue-600">
                  Report Preview
                </p>

                <h2 className="mt-1 text-lg font-bold text-slate-900">
                  {selectedReport.reportName}
                </h2>
              </div>

              <button
                onClick={() =>
                  setSelectedReport(null)
                }
                className="rounded-lg p-2 text-slate-400 transition hover:bg-slate-100 hover:text-slate-700"
              >
                <FiX className="h-5 w-5" />
              </button>

            </div>

            {/* Report Content */}
            <div className="space-y-6 p-6">

              {/* Report details */}
              <div className="grid grid-cols-2 gap-4 rounded-xl bg-slate-50 p-5 sm:grid-cols-4">

                <div>
                  <p className="text-xs text-slate-400">
                    Report ID
                  </p>

                  <p className="mt-1 text-sm font-semibold text-slate-800">
                    {selectedReport.id}
                  </p>
                </div>

                <div>
                  <p className="text-xs text-slate-400">
                    Patient
                  </p>

                  <p className="mt-1 text-sm font-semibold text-slate-800">
                    {selectedReport.patientName}
                  </p>
                </div>

                <div>
                  <p className="text-xs text-slate-400">
                    Type
                  </p>

                  <p className="mt-1 text-sm font-semibold text-slate-800">
                    {selectedReport.reportType}
                  </p>
                </div>

                <div>
                  <p className="text-xs text-slate-400">
                    Generated
                  </p>

                  <p className="mt-1 text-sm font-semibold text-slate-800">
                    {selectedReport.generatedDate}
                  </p>
                </div>

              </div>

              {/* Dummy report sections */}
              <div>
                <h3 className="text-sm font-bold text-slate-900">
                  Clinical Summary
                </h3>

                <p className="mt-2 text-sm leading-7 text-slate-600">
                  This report contains the clinical information,
                  AI-assisted analysis, risk assessment, and
                  relevant findings associated with the selected
                  patient case.
                </p>
              </div>

              <div>
                <h3 className="text-sm font-bold text-slate-900">
                  Assessment
                </h3>

                <p className="mt-2 text-sm leading-7 text-slate-600">
                  The available patient information has been
                  reviewed and analyzed through the MedIntel
                  clinical decision support workflow.
                </p>
              </div>

              <div>
                <h3 className="text-sm font-bold text-slate-900">
                  Recommendations
                </h3>

                <p className="mt-2 text-sm leading-7 text-slate-600">
                  Further clinical evaluation and professional
                  review are recommended based on the findings
                  presented in this report.
                </p>
              </div>

              {/* Actions */}
              <div className="flex flex-col-reverse gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:justify-end">

                <Button
                  variant="outline"
                  onClick={() =>
                    setSelectedReport(null)
                  }
                >
                  Close
                </Button>

                <Button
                  icon={FiDownload}
                  onClick={() =>
                    handleDownload(selectedReport)
                  }
                >
                  Download PDF
                </Button>

              </div>

            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default Reports