import { useEffect, useMemo, useState } from "react"
import { useNavigate } from "react-router-dom"
import {
  FiDownload,
  FiEye,
  FiFileText,
  FiSearch,
  FiX,
} from "react-icons/fi"
import { toast } from "react-toastify"

import Card from "../../components/Card"
import Badge from "../../components/Badge"
import Button from "../../components/Button"

import { getCases } from "../../services/cases"
import {
  getReportById,
  downloadReport,
} from "../../services/reports"

const Reports = () => {
  const navigate = useNavigate()

  const [cases, setCases] = useState([])
  const [search, setSearch] = useState("")
  const [selectedCase, setSelectedCase] = useState(null)

  const [loading, setLoading] = useState(true)
  const [downloading, setDownloading] = useState(null)
  const [viewing, setViewing] = useState(null)

  // Load real cases from backend
  useEffect(() => {
    const loadCases = async () => {
      try {
        setLoading(true)

        const data = await getCases()

        setCases(Array.isArray(data) ? data : [])
      } catch (error) {
        console.error("Failed to load cases:", error)

        toast.error(
          "Unable to load clinical reports."
        )
      } finally {
        setLoading(false)
      }
    }

    loadCases()
  }, [])

  // Search
  const filteredCases = useMemo(() => {
    const value = search.toLowerCase().trim()

    if (!value) {
      return cases
    }

    return cases.filter((item) => {
      const patientName =
        item.patientName?.toLowerCase() || ""

      const patientId =
        String(item.id || "").toLowerCase()

      const status =
        item.status?.toLowerCase() || ""

      return (
        patientName.includes(value) ||
        patientId.includes(value) ||
        status.includes(value)
      )
    })
  }, [cases, search])

  // View PDF
  const handleView = async (patientCase) => {
    try {
      setViewing(patientCase.id)

      const blob = await getReportById(patientCase.id)

      const url = window.URL.createObjectURL(
        new Blob([blob], {
          type: "application/pdf",
        })
      )

      window.open(url, "_blank")

      // Give browser time to open the PDF
      setTimeout(() => {
        window.URL.revokeObjectURL(url)
      }, 60000)
    } catch (error) {
      console.error("Failed to view report:", error)

      toast.error(
        "Unable to open the PDF report."
      )
    } finally {
      setViewing(null)
    }
  }

  // Download PDF
  const handleDownload = async (patientCase) => {
    try {
      setDownloading(patientCase.id)

      await downloadReport(
        patientCase.id,
        patientCase.patientName
      )

      toast.success(
        "PDF report downloaded successfully."
      )
    } catch (error) {
      console.error(
        "Failed to download report:",
        error
      )

      toast.error(
        "Unable to download the PDF report."
      )
    } finally {
      setDownloading(null)
    }
  }

  return (
    <div className="mx-auto max-w-[1400px] space-y-6">

      {/* Header */}
      <div>
        <p className="text-sm font-medium text-blue-600">
          Clinical Documentation
        </p>

        <h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">
          Reports
        </h1>

        <p className="mt-2 text-sm text-slate-500">
          View and download clinical reports generated by
          MedIntel.
        </p>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">

        {/* Total */}
        <Card>
          <div className="flex items-center gap-4">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-600">
              <FiFileText className="h-5 w-5" />
            </div>

            <div>
              <p className="text-xs text-slate-400">
                Total Cases
              </p>

              <p className="text-xl font-bold text-slate-900">
                {cases.length}
              </p>
            </div>
          </div>
        </Card>

        {/* Generated */}
        <Card>
          <div className="flex items-center gap-4">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600">
              <FiFileText className="h-5 w-5" />
            </div>

            <div>
              <p className="text-xs text-slate-400">
                Reports Available
              </p>

              <p className="text-xl font-bold text-slate-900">
                {cases.length}
              </p>
            </div>
          </div>
        </Card>

        {/* Showing */}
        <Card>
          <div className="flex items-center gap-4">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-purple-50 text-purple-600">
              <FiDownload className="h-5 w-5" />
            </div>

            <div>
              <p className="text-xs text-slate-400">
                Showing
              </p>

              <p className="text-xl font-bold text-slate-900">
                {filteredCases.length}
              </p>
            </div>
          </div>
        </Card>

      </div>

      {/* Search */}
      <Card>
        <div className="relative">
          <FiSearch className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />

          <input
            type="text"
            value={search}
            onChange={(e) =>
              setSearch(e.target.value)
            }
            placeholder="Search patient or case ID..."
            className="w-full rounded-lg border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-4 text-sm outline-none transition focus:border-blue-500 focus:bg-white focus:ring-2 focus:ring-blue-100"
          />
        </div>
      </Card>

      {/* Reports table */}
      <Card className="overflow-hidden">

        <div className="border-b border-slate-100 px-5 py-4">
          <p className="text-sm text-slate-500">
            Showing{" "}
            <span className="font-semibold text-slate-800">
              {filteredCases.length}
            </span>{" "}
            reports
          </p>
        </div>

        {loading ? (
          <div className="flex min-h-[280px] items-center justify-center">
            <p className="text-sm text-slate-500">
              Loading reports...
            </p>
          </div>
        ) : filteredCases.length > 0 ? (

          <div className="overflow-x-auto">

            <table className="w-full min-w-[900px] text-left">

              <thead>
                <tr className="border-b border-slate-100 bg-slate-50/70">

                  <th className="px-5 py-3 text-xs font-semibold uppercase tracking-wider text-slate-400">
                    Report
                  </th>

                  <th className="px-5 py-3 text-xs font-semibold uppercase tracking-wider text-slate-400">
                    Patient
                  </th>

                  <th className="px-5 py-3 text-xs font-semibold uppercase tracking-wider text-slate-400">
                    Urgency
                  </th>

                  <th className="px-5 py-3 text-xs font-semibold uppercase tracking-wider text-slate-400">
                    Status
                  </th>

                  <th className="px-5 py-3 text-xs font-semibold uppercase tracking-wider text-slate-400">
                    Created
                  </th>

                  <th className="px-5 py-3 text-right text-xs font-semibold uppercase tracking-wider text-slate-400">
                    Actions
                  </th>

                </tr>
              </thead>

              <tbody>

                {filteredCases.map((patientCase) => (

                  <tr
                    key={patientCase.id}
                    className="border-b border-slate-100 transition hover:bg-slate-50/60"
                  >

                    {/* Report */}
                    <td className="px-5 py-4">

                      <div className="flex items-center gap-3">

                        <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-600">
                          <FiFileText className="h-4 w-4" />
                        </div>

                        <div>
                          <p className="text-sm font-semibold text-slate-800">
                            Clinical Report
                          </p>

                          <p className="mt-0.5 text-xs text-slate-400">
                            Case #{patientCase.id}
                          </p>
                        </div>

                      </div>

                    </td>

                    {/* Patient */}
                    <td className="px-5 py-4">

                      <button
                        onClick={() =>
                          navigate(
                            `/cases/${patientCase.id}`
                          )
                        }
                        className="text-left"
                      >
                        <p className="text-sm font-medium text-blue-600 hover:text-blue-700">
                          {patientCase.patientName}
                        </p>

                        <p className="text-xs text-slate-400">
                          Patient ID: {patientCase.id}
                        </p>
                      </button>

                    </td>

                    {/* Urgency */}
                    <td className="px-5 py-4">

                      <Badge
                        variant={
                          patientCase.urgencyLevel ===
                          "critical"
                            ? "danger"
                            : patientCase.urgencyLevel ===
                              "high"
                            ? "warning"
                            : patientCase.urgencyLevel ===
                              "medium"
                            ? "warning"
                            : "success"
                        }
                      >
                        {patientCase.urgencyLevel
                          ? patientCase.urgencyLevel
                              .charAt(0)
                              .toUpperCase() +
                            patientCase.urgencyLevel.slice(1)
                          : "Unknown"}
                      </Badge>

                    </td>

                    {/* Status */}
                    <td className="px-5 py-4">

                      <Badge variant="info">
                        {patientCase.status || "Waiting"}
                      </Badge>

                    </td>

                    {/* Created */}
                    <td className="whitespace-nowrap px-5 py-4 text-sm text-slate-500">

                      {patientCase.createdAt
                        ? new Date(
                            patientCase.createdAt
                          ).toLocaleString()
                        : "—"}

                    </td>

                    {/* Actions */}
                    <td className="px-5 py-4">

                      <div className="flex justify-end gap-1">

                        {/* View */}
                        <button
                          title="View PDF"
                          disabled={
                            viewing ===
                            patientCase.id
                          }
                          onClick={() =>
                            handleView(patientCase)
                          }
                          className="rounded-lg p-2 text-slate-500 transition hover:bg-blue-50 hover:text-blue-600 disabled:opacity-50"
                        >
                          <FiEye className="h-4 w-4" />
                        </button>

                        {/* Download */}
                        <button
                          title="Download PDF"
                          disabled={
                            downloading ===
                            patientCase.id
                          }
                          onClick={() =>
                            handleDownload(
                              patientCase
                            )
                          }
                          className="rounded-lg p-2 text-slate-500 transition hover:bg-emerald-50 hover:text-emerald-600 disabled:opacity-50"
                        >
                          <FiDownload className="h-4 w-4" />
                        </button>

                      </div>

                    </td>

                  </tr>

                ))}

              </tbody>

            </table>

          </div>

        ) : (

          <div className="flex min-h-[280px] flex-col items-center justify-center text-center">

            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-slate-100">
              <FiSearch className="h-5 w-5 text-slate-400" />
            </div>

            <h3 className="mt-4 text-sm font-semibold text-slate-800">
              No reports found
            </h3>

            <p className="mt-1 text-sm text-slate-500">
              No clinical cases are available.
            </p>

          </div>

        )}

      </Card>

      {/* Information */}
      <div className="rounded-xl border border-amber-100 bg-amber-50 px-5 py-4">

        <div className="flex gap-3">

          <FiFileText className="mt-0.5 h-5 w-5 shrink-0 text-amber-600" />

          <div>
            <p className="text-sm font-semibold text-amber-800">
              Clinical report
            </p>

            <p className="mt-1 text-sm leading-6 text-amber-700">
              Reports are generated from the clinical case
              information stored by MedIntel. Use View to open
              the PDF in a new tab or Download to save it.
            </p>
          </div>

        </div>

      </div>

      {/* Kept for compatibility with existing state */}
      {selectedCase && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4"
          onClick={() =>
            setSelectedCase(null)
          }
        >
          <div
            className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl"
            onClick={(e) =>
              e.stopPropagation()
            }
          >
            <div className="flex items-center justify-between">

              <h2 className="text-lg font-bold text-slate-900">
                {selectedCase.patientName}
              </h2>

              <button
                onClick={() =>
                  setSelectedCase(null)
                }
                className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"
              >
                <FiX className="h-5 w-5" />
              </button>

            </div>
          </div>
        </div>
      )}

    </div>
  )
}

export default Reports